<a href="https://colab.research.google.com/github/KurtGabrielAnduque/CPE-312-BSCPE31S3/blob/main/Assignment_1_1_ML_Tools%2C_Process%2C_and_Your_Learnings_ANDUQUE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font size = 7>Assignment 1.1 ML Tools, Process, and Your Learnings </font>

Name: Kurt Gabriel A. Anduque<br>
Section: BSCPE31S3

In [ ]:
# Connect the google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

1. Summarize the following:
- What is overfitting and underfitting? Provide examples.
- Define cross fold validation. How is it useful?
2. Demonstrate data splitting for training and testing data. Using any preprocessing library in Python on the iris dataset provided in the module.
3. Provide a sample confusion matrix and demonstrate the computation of TP, FP, FN, TN. How can we derive accuracy of the model based on the previously mentioned metrics?

<font size = 6><b>1. Summarize the following:</font>

<font size = 5>What is overfitting and underfitting? Provide examples.</font>

Answer:
- In the field of machine learning when we are training our models we it is necessary to check our model is Underfitting or Overfitting. For the **underfitting**, it is where the model is not learning from the datasets or it does not capture the underlaying trend of the data and does not fit the data well enough. This model occures when has low variance but high bias. For example, we have data points that is parabolic in nature. If we try to fit the linear function with just one parameter, the model will be too simple to follow the curve trend of the data. This will result to a high bias model or poor predictor, wherein we get a consistent answer but these are answers are consistenly wrong. When it come to the overfitting model, it occurs when the model is very complex due to many paremeters. Because of this the model will not just learn the underlying patters in the training dataset but also the noise and random fluctuations in the training set. Which result to low error on training sets but high error on test set. For example you are creating a model to predict the price of a house based on certain features like size, number of bedrooms, and location of the house. You build an over complex model where you use a high degree polynomial regression. This might capture noise or fluctuations in your training set, which result to predict or memorize the exact training values but fails on the test set.

<font size = 5>Define cross fold validation. How is it useful? </font>

Answer:
- It is a method used to evaluate machine learning models on a limited data sample. It is used to estimate the skill of model on useen data. Wherein we split the data into training and test set, under the training set we get a portion of it and use it as a validation set to tune the model parameters and evaluate its performance before using the test set. This technique is useful specially if we are utilizing K-Fold Cross-validation to ensure the model's accuracy and ability of the model to predict new data that was not used in estimating it.

<font size = 6><b>2. Demonstrate data splitting for training and testing data. Using any preprocessing library in Python on the iris dataset provided in the module.</font>

In [ ]:
# import the python libraries for demonstration

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
#Import the Iris dataset

df = pd.read_csv('/content/drive/MyDrive/Iris_Data.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# Clean label name before start splitting
df['species'] = df.species.str.replace('Iris-','')

In [ ]:
df.head(3)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [ ]:
# determine what would be the x and y dataset before we start splitting it into main and test set
# x will be the features of the dataset (characteristics of the flower)
# y will be the target of te dataset (the flower names)
x = df.drop(columns = ['species'])
y = df['species']

In [ ]:
# lets check our x
x.shape

(150, 4)

In [ ]:
# lets check our y
y.shape

(150,)

In [ ]:
print(x.head())
print(y.head())

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [ ]:
# start splitting 80% train 20% test
# add random_state to ensure same split every run of code
x_main,x_test,y_main,y_test = train_test_split(x,y,test_size = 0.2, random_state=20)

In [ ]:
print("train")
print(x_main.shape)
print(y_main.shape)
print('\n')
print("test")
print(x_test.shape)
print(y_test.shape)

train
(120, 4)
(120,)


test
(30, 4)
(30,)

In [ ]:
# when we get the train set it is important to get the validation set to evaluate the model during the training
# Here I just allocate 80% as train set and 20% as validation set to demonstrate splitting of data
x_train,x_val,y_train,y_val = train_test_split(x_main,y_main,test_size=0.2,random_state=20)

In [ ]:
#Final result

print('X')
print(f'train set: {x_train.shape}')
print(f'validation set: {x_val.shape}')
print(f'test: {x_test.shape}')
print('\n')
print('Y')
print(f'train set: {y_train.shape}')
print(f'validation set: {y_val.shape}')
print(f'test set: {y_test.shape}')

X
train set: (96, 4)
validation set: (24, 4)
test: (30, 4)


Y
train set: (96,)
validation set: (24,)
test set: (30,)

<font size = 6><b>3. Provide a sample confusion matrix and demonstrate the computation of TP, FP, FN, TN. How can we derive accuracy of the model based on the previously mentioned metrics?

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

# lets create an example result here:
# true values
true_value =[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0]
# predicted by the model
predicted = [1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0]

# this will get the result of the evaluation of the model using the confusion matrix
cm = confusion_matrix(true_value, predicted,labels= [0,1])
print("Confusion Matrix:")
print("                     prediction negative | prediction positive")
print(f'Condition negative :        {cm[0][0]}                       {cm[0][1]}')
print(f'Condition positive :        {cm[1][0]}                        {cm[1][1]}')

print('\n')
# Extract TP, FP, FN, TN
TN, FP, FN, TP = cm.ravel()
print(f"TP: {TP}, FP: {FP}, FN: {FN}, TN: {TN}")

accuracy_manual = (TP + TN) / (TP + FP + FN + TN) # calculating accuracy using manual
print(f"Accuracy (manual): {accuracy_manual:.2f}")
print(f"Accuracy (sklearn): {accuracy_score(true_value, predicted):.2f}") #calculating accuracy using sklearn

Confusion Matrix:
                     prediction negative | prediction positive
Condition negative :        11                       2
Condition positive :        4                        10


TP: 10, FP: 2, FN: 4, TN: 11
Accuracy (manual): 0.78
Accuracy (sklearn): 0.78

<font size= 6>How can we derive accuracy of the model based on the previously mentioned metrics?</font> <br>
- By observing the formula and the sample confusion matrix. I found that deriving the accuracy of the model is just simply taking the sum of the correct predicitions of the model and then dividing it by the total number of predictions.

<font size = 6>CONCLUSION </font>

- After completing this task, I gained knowledge about the various features of a machine learning model, particularly the undesirable results of an underfitting and overfitting model. Additionally, I was able to use a sample data set to show data splitting for the training and validation sets. Finally, I discovered how to use and apply a sample confusion matrix to determine a model's accuracy.